# Configuration for dessant/label-actions
# Only comments on terminal state changes (close/ship/wontfix/duplicate).
# No comments on intermediate states (accepted, in-progress) to reduce email noise.

# --- SHIPPED: close + lock (no comment) ---
shipped:
  issues:
    close: true
    close-reason: 'completed'
    lock: true
    lock-reason: 'resolved'

# --- WONTFIX: close ---
wontfix:
  issues:
    close: true
    close-reason: 'not planned'

# --- DUPLICATE: close ---
duplicate:
  issues:
    close: true
    close-reason: 'not planned'

# --- ACCEPTED: just remove triage label, no comment ---
accepted:
  issues:
    unlabel: 'triage'

# --- IN-PROGRESS: just remove labels, no comment ---
in-progress:
  issues:
    unlabel:
      - 'triage'
      - 'accepted'

# --- Removing SHIPPED (edge case: premature closure) ---
-shipped:
  issues:
    reopen: true
    unlock: true

# --- Removing WONTFIX (reconsidered) ---
-wontfix:
  issues:
    reopen: true
    label: 'triage'
