name: Bug Report
description: Report a bug or unexpected behaviour
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Tell us what happened, what you expected, and any other details that might help. Screenshots welcome.
      placeholder: "What went wrong? What were you doing when it happened?"
    validations:
      required: true
