name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What would you like to see? What problem does it solve?
      placeholder: "What do you want and why?"
    validations:
      required: true
