name: Help / Question
description: Ask for help with TradeBetter
title: "[Help]: "
labels: ["triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What do you need help with?
      description: Describe your question or what you're stuck on. Include screenshots or links if relevant.
      placeholder: "What are you trying to do?"
    validations:
      required: true
